// <auto-generated />
namespace Project2BurgerMenu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig6));
        
        string IMigrationMetadata.Id
        {
            get { return "202410221111314_mig6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
